---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: team-a
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: my-service:latest
          name: container
          env:
          - name: PRODUCER_URL
            value: "http://producer-service.team-a:5432"
          - name: WORKER_URL
            value: "http://worker-service.team-b:8000"
          - name: SOME_ENV_VAR
            valueFrom:
              configMapKeyRef:
                name: my-configmap-team-a
                key: ENVIRONMENT_VAR_8
          resources:
            limits:
              cpu: 100m
              memory: 128Mi