---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: team-a
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: my-service:latest
          name: container
          env:
          - name: PRODUCER_URL
            value: "http://producer-service.team-b:5000"
          - name: WORKER_URL
            value: "http://worker-service.team-b:5000"
          - name: SOME_ENV_VAR
            valueFrom:
              configMapKeyRef:
                name: my-config # my-config-a
                key: ENVIRONMENT_VAR_8 # ENVIRONMENT_VAR_4
          resources:
            limits:
              cpu: 100m
              memory: 128Mi