apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: dagandersen/middleware:latest
          name: service
          args: 
            - "--system1"
            - "http://system1-service.default:5000"
            - "--system2"
            - "http://prod-system2-service.default:5000"
          ports:
            - containerPort: 5000
          env:
          - name: SYSTEM_1_ACCESS_TOKEN
            valueFrom:
              configMapKeyRef:
                name: prod-system1-config
                key: SYSTEM_1_ACCESS_TOKEN
          - name: SYSTEM_1_USERNAME
            valueFrom:
              configMapKeyRef:
                name: prod-system1-config
                key: SYST3M_1_USERNAME
          - name: REFRESH_INTERVAL
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: INTERVALS_REFRESH 
          resources:
            limits:
              cpu: 100m
              memory: 128Mi