apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: dagandersen/middleware:latest
          name: service
          args: 
            - "--database"
            - "http://database-service.default:5000"
            - "--worker"
            - "http://prod-worker-service.default:5000"
          ports:
            - containerPort: 5000
          env:
          - name: DATABASE_ACCESS_TOKEN
            valueFrom:
              configMapKeyRef:
                name: prod-database-config
                key: DATABASE_ACCESS_TOKEN
          - name: DATABASE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: prod-database-config
                key: SYST3M_1_USERNAME
          - name: REFRESH_INTERVAL
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: INTERVALS_REFRESH 
          resources:
            limits:
              cpu: 100m
              memory: 128Mi