apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
              env:
                - name: "SECRET2"
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: my-secret
                - name: "CONFIG2"
                  valueFrom:
                    configMapKeyRef:
                      key: key
                      name: my-config
          restartPolicy: OnFailure