apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-b
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        system: my-system
    spec:
      containers:
        - name: echo-server
          image: "dagandersen/echo-server"
          env:
            - name: "SECRET2"
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
            - name: "CONFIG2"
              valueFrom:
                configMapKeyRef:
                  key: key
                  name: my-config
          resources:
            limits:
              cpu: "250m"
              memory: "50Mi"
