apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
spec:
  containers:
    - name: echo-server
      image: "dagandersen/echo-server"
      resources:
        limits:
          cpu: "250m"
          memory: "1Gi" 