apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  ports:
    - name: httpss
      port: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-b
spec:
  ports:
    - name: http
      port: 3030
  selector:
    app: my-app
    system: my-system
