apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: php-redis
          image: gcr.io/google_samples/gb-frontend:v3
          env:
            - name: "SECRET2"
              valueFrom:
                secretKeyRef:
                  key: password
                  name: my-secret
            - name: "CONFIG2"
              valueFrom:
                configMapKeyRef:
                  key: key
                  name: my-config
