apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-a
  labels:
    app: system-a
spec:
  selector:
    matchLabels:
      app: system-a
  template:
    metadata:
      labels:
        app: system-a
    spec:
      containers:
        - image: org/system-a:latest
          name: container-a
          args: ["--system-b-host", "service-b"]
          ports:
            - containerPort: 5000
          env:
            - name: THIRD_PARTY_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map-a
                  key: THIRD_PARTY_API_HOST
            - name: THIRD_PARTY_API_ACCESS_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: config-a
                  key: THIRD_PARTY_API_TOKEN
          resources:
            limits:
              cpu: 100m
              memory: 128Mi