apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: backend
  name: backend-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: org/backend:release
          name: backend
          ports:
            - containerPort: 5000
          args:
            - "--BACKEND_ADDRESS"
            - "postgres-svc"
          env:
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: DB_PORT
            - name: DB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: DB_TABLE
          resources:
            limits:
              cpu: 100m
              memory: 128Mi