---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: frontend
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/eficode-academy/quotes-flask-frontend:release
          name: frontend
          ports:
            - containerPort: 5000
          env:
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: BACKEND_HOST
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: BACKEND_PORT
          resources: 
            limits:
              cpu: 100m
              memory: 128Mi